export const words = [
    { english: "Accept", pron_pre: "/acépt/", third_person: "Accepts", pron_thp: "/acépts/", gerundio: "Accepting", pron_ger: "/acéptin/", past: "Accepted", pron_past: "/acéptid/", spanish: "aceptar" },
    { english: "Add", pron_pre: "/ad/", third_person: "Adds", pron_thp: "/ads/", gerundio: "Adding", pron_ger: "/ádin/", past: "Added", pron_past: "/ádid/", spanish: "añadir / sumar" },
    { english: "Admire", pron_pre: "/admaiar/", third_person: "Admires", pron_thp: "/admáiars/", gerundio: "Admiring", pron_ger: "/admáirin/", past: "Admired", pron_past: "/admáiard/", spanish: "admirar" },
    { english: "Admit", pron_pre: "/admint/", third_person: "Admits", pron_thp: "/admints/", gerundio: "Admitting", pron_ger: "/admítin/", past: "Admitted", pron_past: "/admítid/", spanish: "admitir" },
    { english: "Advise", pron_pre: "/advais/", third_person: "Advises", pron_thp: "/adváisiz/", gerundio: "Advising", pron_ger: "/adváisin/", past: "Advised", pron_past: "/adváisd/", spanish: "aconsejar" },
    { english: "Afford", pron_pre: "/aford/", third_person: "Affords", pron_thp: "/afórds/", gerundio: "Affording", pron_ger: "/afórdin/", past: "Afforded", pron_past: "/afórdid/", spanish: "permitirse (económicamente)" },
    { english: "Agree", pron_pre: "/agri/", third_person: "Agrees", pron_thp: "/agris/", gerundio: "Agreeing", pron_ger: "/agriin/", past: "Agreed", pron_past: "/agrid/", spanish: "estar de acuerdo" },
    { english: "Alert", pron_pre: "/alert/", third_person: "Alerts", pron_thp: "/alerts/", gerundio: "Alerting", pron_ger: "/alértin/", past: "Alerted", pron_past: "/alértid/", spanish: "alertar" },
    { english: "Allow", pron_pre: "/alou/", third_person: "Allows", pron_thp: "/aláus/", gerundio: "Allowing", pron_ger: "/aláuin/", past: "Allowed", pron_past: "/aláud/", spanish: "permitir" },
    { english: "Amuse", pron_pre: "/amius/", third_person: "Amuses", pron_thp: "/amiúsiz/", gerundio: "Amusing", pron_ger: "/amiúsin/", past: "Amused", pron_past: "/amiúsd/", spanish: "divertir / entretener" },
    { english: "Analyse", pron_pre: "/enalais/", third_person: "Analyses", pron_thp: "/enaláisiz/", gerundio: "Analysing", pron_ger: "/enaláisin/", past: "Analysed", pron_past: "/enaláisd/", spanish: "analizar" },
    { english: "Announce", pron_pre: "/anauns/", third_person: "Announces", pron_thp: "/anáunsiz/", gerundio: "Announcing", pron_ger: "/anáunsin/", past: "Announced", pron_past: "/anáunst/", spanish: "anunciar" },
    { english: "Annoy", pron_pre: "/anoi/", third_person: "Annoys", pron_thp: "/anóis/", gerundio: "Annoying", pron_ger: "/anóiin/", past: "Annoyed", pron_past: "/anóid/", spanish: "molestar / fastidiar" },
    { english: "Answer", pron_pre: "/enser/", third_person: "Answers", pron_thp: "/énsers/", gerundio: "Answering", pron_ger: "/énserin/", past: "Answered", pron_past: "/énserd/", spanish: "responder / contestar" },
    { english: "Apologise", pron_pre: "/apoloyais/", third_person: "Apologises", pron_thp: "/apoloyáisiz/", gerundio: "Apologising", pron_ger: "/apoloyáisin/", past: "Apologised", pron_past: "/apoloyáisd/", spanish: "disculparse" },
    { english: "Appear", pron_pre: "/apíer/", third_person: "Appears", pron_thp: "/apíers/", gerundio: "Appearing", pron_ger: "/apíerin/", past: "Appeared", pron_past: "/apíerd/", spanish: "aparecer" },
    { english: "Applaud", pron_pre: "/aplad/", third_person: "Applauds", pron_thp: "/aplads/", gerundio: "Applauding", pron_ger: "/apláudin/", past: "Applauded", pron_past: "/apláudid/", spanish: "aplaudir" },
    { english: "Approve", pron_pre: "/aprút/", third_person: "Approves", pron_thp: "/aprúvs/", gerundio: "Approving", pron_ger: "/aprúvin/", past: "Approved", pron_past: "/aprúvd/", spanish: "aprobar" },
    { english: "Arrange", pron_pre: "/arréindch/", third_person: "Arranges", pron_thp: "/arréindchiz/", gerundio: "Arranging", pron_ger: "/arréindchin/", past: "Arranged", pron_past: "/arréindchd/", spanish: "arreglar / organizar" },
    { english: "Arrest", pron_pre: "/arrést/", third_person: "Arrests", pron_thp: "/arrésts/", gerundio: "Arresting", pron_ger: "/arréstin/", past: "Arrested", pron_past: "/arréstid/", spanish: "arrestar / detener" },
    { english: "Arrive", pron_pre: "/arráif/", third_person: "Arrives", pron_thp: "/arráivs/", gerundio: "Arriving", pron_ger: "/arráivin/", past: "Arrived", pron_past: "/arráivd/", spanish: "llegar" },
    { english: "Ask", pron_pre: "/ask/", third_person: "Asks", pron_thp: "/asks/", gerundio: "Asking", pron_ger: "/áskin/", past: "Asked", pron_past: "/askt/", spanish: "preguntar / pedir" },
    { english: "Attack", pron_pre: "/atáck/", third_person: "Attacks", pron_thp: "/atácks/", gerundio: "Attacking", pron_ger: "/atáckin/", past: "Attacked", pron_past: "/atáckt/", spanish: "atacar" },
    { english: "Attempt", pron_pre: "/atémpt/", third_person: "Attempts", pron_thp: "/atémpts/", gerundio: "Attempting", pron_ger: "/atémptin/", past: "Attempted", pron_past: "/atémptid/", spanish: "intentar / tratar de" },
    { english: "Attend", pron_pre: "/aténd/", third_person: "Attends", pron_thp: "/aténds/", gerundio: "Attending", pron_ger: "/aténdin/", past: "Attended", pron_past: "/aténdid/", spanish: "asistir / atender" },
    { english: "Attract", pron_pre: "/atráct/", third_person: "Attracts", pron_thp: "/atrácts/", gerundio: "Attracting", pron_ger: "/atráctin/", past: "Attracted", pron_past: "/atráctid/", spanish: "atraer" },
    { english: "Avoid", pron_pre: "/avóid/", third_person: "Avoids", pron_thp: "/avóids/", gerundio: "Avoiding", pron_ger: "/avóidin/", past: "Avoided", pron_past: "/avóidid/", spanish: "evitar" },
    { english: "Bake", pron_pre: "/béik/", third_person: "Bakes", pron_thp: "/béiks/", gerundio: "Baking", pron_ger: "/béikin/", past: "Baked", pron_past: "/béikt/", spanish: "hornear" },
    { english: "Balance", pron_pre: "/bálans/", third_person: "Balances", pron_thp: "/bálansiz/", gerundio: "Balancing", pron_ger: "/bálansin/", past: "Balanced", pron_past: "/bálanst/", spanish: "equilibrar" },
    { english: "Bathe", pron_pre: "/béid baz/", third_person: "Bathes", pron_thp: "/béidz/", gerundio: "Bathing", pron_ger: "/béidin/", past: "Bathed", pron_past: "/béid-d/", spanish: "bañar(se)" },
    { english: "Beg", pron_pre: "/beg/", third_person: "Begs", pron_thp: "/begs/", gerundio: "Begging", pron_ger: "/bégin/", past: "Begged", pron_past: "/begd/", spanish: "suplicar / rogar" },
    { english: "Behave", pron_pre: "/bijéiv/", third_person: "Behaves", pron_thp: "/bijéivs/", gerundio: "Behaving", pron_ger: "/bijéivin/", past: "Behaved", pron_past: "/bijéivd/", spanish: "comportarse" },
    { english: "Belong", pron_pre: "/bilóng/", third_person: "Belongs", pron_thp: "/bilóngs/", gerundio: "Belonging", pron_ger: "/bilóngin/", past: "Belonged", pron_past: "/bilóngd/", spanish: "pertenecer" },
    { english: "Bless", pron_pre: "/bles/", third_person: "Blesses", pron_thp: "/blésiz/", gerundio: "Blessing", pron_ger: "/blésin/", past: "Blessed", pron_past: "/blest/", spanish: "bendecir" },
    { english: "Blind", pron_pre: "/bláind/", third_person: "Blinds", pron_thp: "/bláinds/", gerundio: "Blinding", pron_ger: "/bláindin/", past: "Blinded", pron_past: "/bláindid/", spanish: "cegar" },
    { english: "Blink", pron_pre: "/blenk/", third_person: "Blinks", pron_thp: "/blenks/", gerundio: "Blinking", pron_ger: "/blénkin/", past: "Blinked", pron_past: "/blenkt/", spanish: "parpadear" },
    { english: "Blush", pron_pre: "/blash/", third_person: "Blushes", pron_thp: "/bláshiz/", gerundio: "Blushing", pron_ger: "/bláshin/", past: "Blushed", pron_past: "/blasht/", spanish: "sonrojarse" },
    { english: "Book", pron_pre: "/buk/", third_person: "Books", pron_thp: "/buks/", gerundio: "Booking", pron_ger: "/búkin/", past: "Booked", pron_past: "/bukt/", spanish: "reservar" },
    { english: "Bore", pron_pre: "/bor/", third_person: "Bores", pron_thp: "/bors/", gerundio: "Boring", pron_ger: "/bórin/", past: "Bored", pron_past: "/bord/", spanish: "aburrir" },
    { english: "Borrow", pron_pre: "/bórróu/", third_person: "Borrows", pron_thp: "/bórróus/", gerundio: "Borrowing", pron_ger: "/bórróuin/", past: "Borrowed", pron_past: "/bórróud/", spanish: "pedir prestado" },
    { english: "Bounce", pron_pre: "/báuns/", third_person: "Bounces", pron_thp: "/báunsiz/", gerundio: "Bouncing", pron_ger: "/báunsin/", past: "Bounced", pron_past: "/báunst/", spanish: "rebotar / saltar" },
    { english: "Breathe", pron_pre: "/brid/", third_person: "Breathes", pron_thp: "/brids/", gerundio: "Breathing", pron_ger: "/brídin/", past: "Breathed", pron_past: "/bridd/", spanish: "Respirar" },
    { english: "Brush", pron_pre: "/brash/", third_person: "Brushes", pron_thp: "/bráshiz/", gerundio: "Brushing", pron_ger: "/bráshin/", past: "Brushed", pron_past: "/brasht/", spanish: "Cepillar" },
    { english: "Bury", pron_pre: "/béri/", third_person: "Buries", pron_thp: "/béris/", gerundio: "Burying", pron_ger: "/bériin/", past: "Buried", pron_past: "/bérid/", spanish: "Enterrar" },
    { english: "Calculate", pron_pre: "/kálkiuleit/", third_person: "Calculates", pron_thp: "/kálkiuleits/", gerundio: "Calculating", pron_ger: "/kálkiuleitin/", past: "Calculated", pron_past: "/kálkiuleitid/", spanish: "Calcular" },
    { english: "Call", pron_pre: "/kol/", third_person: "Calls", pron_thp: "/kols/", gerundio: "Calling", pron_ger: "/kólin/", past: "Called", pron_past: "/kold/", spanish: "llamar" },
    { english: "Camp", pron_pre: "/kamp/", third_person: "Camps", pron_thp: "/kamps/", gerundio: "Camping", pron_ger: "/kámpin/", past: "Camped", pron_past: "/kampt/", spanish: "Acampar" },
    { english: "Cancel", pron_pre: "/kánsel/", third_person: "Cancels", pron_thp: "/kánsels/", gerundio: "Canceling", pron_ger: "/kánselin/", past: "Canceled", pron_past: "/kánseld/", spanish: "Cancelar" },
    { english: "Care", pron_pre: "/ker/", third_person: "Cares", pron_thp: "/kers/", gerundio: "Caring", pron_ger: "/kérin/", past: "Cared", pron_past: "/kerd/", spanish: "Cuidar / Importar" },
    { english: "Cause", pron_pre: "/koz/", third_person: "Causes", pron_thp: "/kóziz/", gerundio: "Causing", pron_ger: "/kózin/", past: "Caused", pron_past: "/kozd/", spanish: "Causar" },
    { english: "Challenge", pron_pre: "/chálindz/", third_person: "Challenges", pron_thp: "/chálindziz/", gerundio: "Challenging", pron_ger: "/chálindzin/", past: "Challenged", pron_past: "/chálindzd/", spanish: "Desafiar" },
    { english: "Change", pron_pre: "/chéindz/", third_person: "Changes", pron_thp: "/chéindziz/", gerundio: "Changing", pron_ger: "/chéindzin/", past: "Changed", pron_past: "/chéindzd/", spanish: "Cambiar" },
    { english: "Charge", pron_pre: "/chárdz/", third_person: "Charges", pron_thp: "/chárdziz/", gerundio: "Charging", pron_ger: "/chárdzin/", past: "Charged", pron_past: "/chárdzd/", spanish: "Cargar (precio o energía)" },
    { english: "Chase", pron_pre: "/chéis/", third_person: "Chases", pron_thp: "/chéisiz/", gerundio: "Chasing", pron_ger: "/chéisin/", past: "Chased", pron_past: "/chéist/", spanish: "Perseguir" },
    { english: "Cheat", pron_pre: "/chit/", third_person: "Cheats", pron_thp: "/chits/", gerundio: "Cheating", pron_ger: "/chítin/", past: "Cheated", pron_past: "/chítid/", spanish: "Engañar / Hacer trampa" },
    { english: "Check", pron_pre: "/chek/", third_person: "Checks", pron_thp: "/cheks/", gerundio: "Checking", pron_ger: "/chékin/", past: "Checked", pron_past: "/chekt/", spanish: "Revisar / Comprobar" },
    { english: "Cheer", pron_pre: "/chir/", third_person: "Cheers", pron_thp: "/chirs/", gerundio: "Cheering", pron_ger: "/chírin/", past: "Cheered", pron_past: "/chird/", spanish: "Alegrar / Animar" },
    { english: "Chew", pron_pre: "/chu/", third_person: "Chews", pron_thp: "/chus/", gerundio: "Chewing", pron_ger: "/chúin/", past: "Chewed", pron_past: "/chud/", spanish: "Masticar" },
    { english: "Claim", pron_pre: "/kleim/", third_person: "Claims", pron_thp: "/kleims/", gerundio: "Claiming", pron_ger: "/kléimin/", past: "Claimed", pron_past: "/kleimd/", spanish: "Reclamar / Afirmar" },
    { english: "Clap", pron_pre: "/kláp/", third_person: "Claps", pron_thp: "/kláps/", gerundio: "Clapping", pron_ger: "/klápin/", past: "Clapped", pron_past: "/klápt/", spanish: "Aplaudir" },
    { english: "Clean", pron_pre: "/klin/", third_person: "Cleans", pron_thp: "/klins/", gerundio: "Cleaning", pron_ger: "/klínin/", past: "Cleaned", pron_past: "/klind/", spanish: "Limpiar" },
    { english: "Clear", pron_pre: "/klíar/", third_person: "Clears", pron_thp: "/klíars/", gerundio: "Clearing", pron_ger: "/klíarin/", past: "Cleared", pron_past: "/klíard/", spanish: "Aclarar / Despejar" },
    { english: "Close", pron_pre: "/klóus/", third_person: "Closes", pron_thp: "/klóusiz/", gerundio: "Closing", pron_ger: "/klóusin/", past: "Closed", pron_past: "/klóusd/", spanish: "Cerrar" },
    { english: "Collect", pron_pre: "/kolekt/", third_person: "Collects", pron_thp: "/kolékts/", gerundio: "Collecting", pron_ger: "/koléktin/", past: "Collected", pron_past: "/koléktid/", spanish: "Recoleccionar / Coleccionar" },
    { english: "Comb", pron_pre: "/koum/", third_person: "Combs", pron_thp: "/koums/", gerundio: "Combing", pron_ger: "/kóumin/", past: "Combed", pron_past: "/koumd/", spanish: "Peinar" },
    { english: "Compare", pron_pre: "/kompér/", third_person: "Compares", pron_thp: "/kompérs/", gerundio: "Comparing", pron_ger: "/kompérin/", past: "Compared", pron_past: "/kompérd/", spanish: "Comparar" },
    { english: "Compete", pron_pre: "/kompít/", third_person: "Competes", pron_thp: "/kompíts/", gerundio: "Competing", pron_ger: "/kompítin/", past: "Competed", pron_past: "/kompítid/", spanish: "Competir" },
    { english: "Complain", pron_pre: "/kompléin/", third_person: "Complains", pron_thp: "/kompléins/", gerundio: "Complaining", pron_ger: "/kompléinin/", past: "Complained", pron_past: "/kompléind/", spanish: "Quejarse" },
    { english: "Complete", pron_pre: "/komplít/", third_person: "Completes", pron_thp: "/komplíts/", gerundio: "Completing", pron_ger: "/komplítin/", past: "Completed", pron_past: "/komplítid/", spanish: "Completar" },
    { english: "Encourage", pron_pre: "/incorch/", third_person: "Encourages", pron_thp: "/inkórindchiz/", gerundio: "Encouraging", pron_ger: "/inkórindchin/", past: "Encouraged", pron_past: "/inkórindchd/", spanish: "animar / alentar" },
    { english: "Expect", pron_pre: "/ekspékt/", third_person: "Expects", pron_thp: "/ekspékts/", gerundio: "Expecting", pron_ger: "/ekspéktin/", past: "Expected", pron_past: "/ekspéktid/", spanish: "esperar" },
    { english: "Improve", pron_pre: "/imprúv/", third_person: "Improves", pron_thp: "/imprúvs/", gerundio: "Improving", pron_ger: "/imprúvin/", past: "Improved", pron_past: "/imprúvd/", spanish: "mejorar" },
    { english: "Marry", pron_pre: "/márri/", third_person: "Marries", pron_thp: "/márris/", gerundio: "Marrying", pron_ger: "/márriin/", past: "Married", pron_past: "/márrid/", spanish: "casarse" },
    { english: "Suspect", pron_pre: "/saspékt/", third_person: "Suspects", pron_thp: "/saspékts/", gerundio: "Suspecting", pron_ger: "/saspéktin/", past: "Suspected", pron_past: "/saspéktid/", spanish: "sospechar" },
    { english: "Travel", pron_pre: "/trável/", third_person: "Travels", pron_thp: "/trávels/", gerundio: "Traveling", pron_ger: "/trávelin/", past: "Traveled", pron_past: "/tráveld/", spanish: "viajar" },
    { english: "Try", pron_pre: "/trái/", third_person: "Tries", pron_thp: "/tráis/", gerundio: "Trying", pron_ger: "/tráiin/", past: "Tried", pron_past: "/tráid/", spanish: "intentar" }
];

export const wordsExamples = [
    { english: "Accept", present: "I accept the challenge.", past: "She accepted the job offer.", gerund: "They are accepting new students." },
    { english: "Add", present: "We add sugar to the coffee.", past: "He added your name to the list.", gerund: "I am adding more details." },
    { english: "Admire", present: "I admire your courage.", past: "They admired the sunset.", gerund: "She is admiring the painting." },
    { english: "Admit", present: "You admit the truth.", past: "He admitted his mistake.", gerund: "She is admitting her faults." },
    { english: "Advise", present: "I advise you to stay.", past: "The doctor advised me to rest.", gerund: "He is advising the team." },
    { english: "Afford", present: "I can't afford that car.", past: "They afforded a nice house.", gerund: "We are affording this trip now." },
    { english: "Agree", present: "I agree with you.", past: "They agreed on the price.", gerund: "We are finally agreeing." },
    { english: "Alert", present: "Dogs alert their owners.", past: "The guard alerted the police.", gerund: "The system is alerting us." },
    { english: "Allow", present: "They allow pets here.", past: "She allowed me to go.", gerund: "The teacher is allowing it." },
    { english: "Amuse", present: "The clown amuses the kids.", past: "The joke amused everyone.", gerund: "This movie is amusing me." },
    { english: "Analyse", present: "I analyse the data.", past: "They analysed the results.", gerund: "He is analysing the blood." },
    { english: "Announce", present: "They announce the winner.", past: "She announced her wedding.", gerund: "The pilot is announcing the landing." },
    { english: "Annoy", present: "Loud noises annoy me.", past: "The rain annoyed us.", gerund: "You are annoying your sister." },
    { english: "Answer", present: "I answer the phone.", past: "He answered all questions.", gerund: "She is answering the emails." },
    { english: "Apologise", present: "I apologise for being late.", past: "He apologised yesterday.", gerund: "They are apologising for the noise." },
    { english: "Appear", present: "Stars appear at night.", past: "A ghost appeared in the room.", gerund: "He is appearing on TV." },
    { english: "Applaud", present: "People applaud the show.", past: "They applauded the speech.", gerund: "Everyone is applauding." },
    { english: "Approve", present: "The boss approves the plan.", past: "She approved the budget.", gerund: "They are approving the loan." },
    { english: "Arrange", present: "I arrange the books.", past: "He arranged a meeting.", gerund: "We are arranging the party." },
    { english: "Arrest", present: "Police arrest criminals.", past: "They arrested the thief.", gerund: "The officer is arresting him." },
    { english: "Arrive", present: "I arrive at 8 AM.", past: "The train arrived late.", gerund: "They are arriving now." },
    { english: "Ask", present: "I ask for help.", past: "She asked a question.", gerund: "He is asking for more time." },
    { english: "Attack", present: "Wolves attack together.", past: "The cat attacked the mouse.", gerund: "They are attacking the fort." },
    { english: "Attempt", present: "I attempt the exam.", past: "He attempted to climb.", gerund: "She is attempting a new record." },
    { english: "Attend", present: "I attend the class.", past: "She attended the wedding.", gerund: "They are attending the concert." },
    { english: "Attract", present: "Magnets attract metal.", past: "The park attracted many people.", gerund: "The offer is attracting clients." },
    { english: "Avoid", present: "I avoid traffic.", past: "He avoided the question.", gerund: "She is avoiding me." },
    { english: "Bake", present: "I bake bread every day.", past: "She baked a delicious cake.", gerund: "We are baking cookies." },
    { english: "Balance", present: "I balance my work and life.", past: "He balanced on the rope.", gerund: "She is balancing the checkbook." },
    { english: "Bathe", present: "I bathe the dog.", past: "He bathed in the river.", gerund: "The baby is bathing." },
    { english: "Beg", present: "I beg your pardon.", past: "He begged for mercy.", gerund: "They are begging for help." },
    { english: "Behave", present: "Children behave well.", past: "He behaved badly at school.", gerund: "She is behaving strangely." },
    { english: "Belong", present: "The key belongs to me.", past: "It belonged to my father.", gerund: "This is finally belonging to us." },
    { english: "Bless", present: "The priest blesses them.", past: "God blessed our family.", gerund: "She is blessing the food." },
    { english: "Blind", present: "The sun blinds me.", past: "The lights blinded him.", gerund: "The flash is blinding us." },
    { english: "Blink", present: "I blink when it's bright.", past: "She blinked twice.", gerund: "He is blinking a lot." },
    { english: "Blush", present: "I blush when I'm nervous.", past: "She blushed after the compliment.", gerund: "He is blushing right now." },
    { english: "Book", present: "I book a hotel room.", past: "They booked the flight.", gerund: "I am booking a table." },
    { english: "Bore", present: "Long movies bore me.", past: "The lecture bored them.", gerund: "This talk is boring me." },
    { english: "Borrow", present: "I borrow books from him.", past: "She borrowed my pen.", gerund: "We are borrowing some money." },
    { english: "Bounce", present: "Balls bounce on the floor.", past: "The ball bounced high.", gerund: "The kids are bouncing on the bed." },
    { english: "Breathe", present: "I breathe fresh air.", past: "He breathed deeply.", gerund: "She is breathing slowly." },
    { english: "Brush", present: "I brush my teeth.", past: "She brushed her hair.", gerund: "He is brushing the dog." },
    { english: "Bury", present: "They bury the treasure.", past: "He buried the old dog.", gerund: "She is burying the plant." },
    { english: "Calculate", present: "I calculate the cost.", past: "She calculated the distance.", gerund: "He is calculating the taxes." },
    { english: "Call", present: "I call my mom.", past: "He called me last night.", gerund: "They are calling for help." },
    { english: "Camp", present: "We camp in the woods.", past: "They camped by the lake.", gerund: "We are camping this weekend." },
    { english: "Cancel", present: "I cancel the order.", past: "She cancelled the meeting.", gerund: "They are cancelling the trip." },
    { english: "Care", present: "I care about you.", past: "He cared for his mother.", gerund: "She is caring for the sick." },
    { english: "Cause", present: "Smoking causes cancer.", past: "The storm caused damage.", gerund: "The leak is causing trouble." },
    { english: "Challenge", present: "I challenge you.", past: "He challenged the decision.", gerund: "They are challenging the law." },
    { english: "Change", present: "I change my clothes.", past: "She changed her mind.", gerund: "The weather is changing." },
    { english: "Charge", present: "I charge my phone.", past: "They charged me $50.", gerund: "He is charging the battery." },
    { english: "Chase", present: "Dogs chase cats.", past: "The police chased the car.", gerund: "She is chasing her dreams." },
    { english: "Cheat", present: "Never cheat in exams.", past: "He cheated on the test.", gerund: "They are cheating at cards." },
    { english: "Check", present: "I check the time.", past: "She checked the oven.", gerund: "He is checking his email." },
    { english: "Cheer", present: "Fans cheer for the team.", past: "They cheered loudly.", gerund: "We are cheering for you." },
    { english: "Chew", present: "I chew slowly.", past: "The dog chewed the shoe.", gerund: "She is chewing gum." },
    { english: "Claim", present: "They claim they are rich.", past: "He claimed the insurance.", gerund: "She is claiming her prize." },
    { english: "Clap", present: "I clap my hands.", past: "The audience clapped.", gerund: "They are clapping for him." },
    { english: "Clean", present: "I clean my room.", past: "He cleaned the kitchen.", gerund: "We are cleaning the house." },
    { english: "Clear", present: "I clear the table.", past: "The sky cleared up.", gerund: "He is clearing the snow." },
    { english: "Close", present: "I close the door.", past: "She closed the window.", gerund: "They are closing the store." },
    { english: "Collect", present: "I collect stamps.", past: "He collected the coins.", gerund: "She is collecting flowers." },
    { english: "Comb", present: "I comb my hair.", past: "She combed her daughter's hair.", gerund: "He is combing his beard." },
    { english: "Compare", present: "I compare the prices.", past: "He compared both cars.", gerund: "She is comparing the notes." },
    { english: "Compete", present: "They compete in sports.", past: "We competed in the race.", gerund: "They are competing now." },
    { english: "Complain", present: "I never complain.", past: "He complained about the food.", gerund: "She is complaining again." },
    { english: "Complete", present: "I complete the task.", past: "She completed the puzzle.", gerund: "He is completing the form." },
    { english: "Encourage", present: "I encourage my friend.", past: "She encouraged me to try.", gerund: "They are encouraging us." },
    { english: "Expect", present: "I expect good news.", past: "He expected a better result.", gerund: "She is expecting a baby." },
    { english: "Improve", present: "I improve my English.", past: "He improved his score.", gerund: "They are improving slowly." },
    { english: "Marry", present: "They marry next month.", past: "They married in June.", gerund: "She is marrying him today." },
    { english: "Suspect", present: "I suspect him.", past: "The police suspected her.", gerund: "They are suspecting a leak." },
    { english: "Travel", present: "I travel every summer.", past: "We traveled to Italy.", gerund: "He is traveling by train." },
    { english: "Try", present: "I try to help.", past: "She tried her best.", gerund: "He is trying to fix it." }
];

export const wordsRegular = [
    { english: "Arise", pron_pre: "/arais/", third_person: "Arises", pron_thp: "/aráisiz/", gerundio: "Arising", pron_ger: "/aráisin/", past: "Arose", pron_past: "/aróus/", spanish: "surgir / levantarse" },
    { english: "Bear", pron_pre: "/verr/", third_person: "Bears", pron_thp: "/bers/", gerundio: "Bearing", pron_ger: "/bérin/", past: "Bore", pron_past: "/bor/", spanish: "soportar / dar a luz" },
    { english: "Beat", pron_pre: "/bit/", third_person: "Beats", pron_thp: "/bits/", gerundio: "Beating", pron_ger: "/bítin/", past: "Beat", pron_past: "/bit/", spanish: "golpear / vencer" },
    { english: "Become", pron_pre: "/bicom/", third_person: "Becomes", pron_thp: "/bicóms/", gerundio: "Becoming", pron_ger: "/bicómin/", past: "Became", pron_past: "/bikeim/", spanish: "convertirse / volverse" },
    { english: "Begin", pron_pre: "/begin/", third_person: "Begins", pron_thp: "/begíns/", gerundio: "Beginning", pron_ger: "/begínin/", past: "Began", pron_past: "/begán/", spanish: "comenzar / empezar" },
    { english: "Bite", pron_pre: "/bait/", third_person: "Bites", pron_thp: "/baits/", gerundio: "Biting", pron_ger: "/báitin/", past: "Bit", pron_past: "/bit/", spanish: "morder" },
    { english: "Bleed", pron_pre: "/blid/", third_person: "Bleeds", pron_thp: "/blids/", gerundio: "Bleeding", pron_ger: "/blídin/", past: "Bled", pron_past: "/bled/", spanish: "sangrar" },
    { english: "Blow", pron_pre: "/blou/", third_person: "Blows", pron_thp: "/blous/", gerundio: "Blowing", pron_ger: "/blóuin/", past: "Blew", pron_past: "/blu/", spanish: "soplar" },
    { english: "Break", pron_pre: "/breik/", third_person: "Breaks", pron_thp: "/breiks/", gerundio: "Breaking", pron_ger: "/bréikin/", past: "Broke", pron_past: "/brouk/", spanish: "romper" },
    { english: "Breed", pron_pre: "/brid/", third_person: "Breeds", pron_thp: "/brids/", gerundio: "Breeding", pron_ger: "/brídin/", past: "Bred", pron_past: "/bred/", spanish: "criar" },
    { english: "Bring", pron_pre: "/bring/", third_person: "Brings", pron_thp: "/brings/", gerundio: "Bringing", pron_ger: "/bríngin/", past: "Brought", pron_past: "/brot/", spanish: "traer" },
    { english: "Build", pron_pre: "/bild/", third_person: "Builds", pron_thp: "/bilds/", gerundio: "Building", pron_ger: "/bíldin/", past: "Built", pron_past: "/bilt/", spanish: "construir" },
    { english: "Burn", pron_pre: "/bern/", third_person: "Burns", pron_thp: "/berns/", gerundio: "Burning", pron_ger: "/bérnin/", past: "Burnt", pron_past: "/bernt/", spanish: "quemar" },
    { english: "Buy", pron_pre: "/bai/", third_person: "Buys", pron_thp: "/bais/", gerundio: "Buying", pron_ger: "/báiin/", past: "Bought", pron_past: "/bot/", spanish: "comprar" },
    { english: "Can", pron_pre: "/ken/", third_person: "Can", pron_thp: "/ken/", gerundio: "---", pron_ger: "---", past: "Could", pron_past: "/cud/", spanish: "poder" },
    { english: "Catch", pron_pre: "/kech/", third_person: "Catches", pron_thp: "/káchiz/", gerundio: "Catching", pron_ger: "/káchin/", past: "Caught", pron_past: "/kot/", spanish: "atrapar / coger" },
    { english: "Choose", pron_pre: "/shus/", third_person: "Chooses", pron_thp: "/shúsiz/", gerundio: "Choosing", pron_ger: "/shúsin/", past: "Chose", pron_past: "/shous/", spanish: "elegir" },
    { english: "Cling", pron_pre: "/cling/", third_person: "Clings", pron_thp: "/clings/", gerundio: "Clinging", pron_ger: "/clíngin/", past: "Clung", pron_past: "/clang/", spanish: "aferrarse" },
    { english: "Come", pron_pre: "/com/", third_person: "Comes", pron_thp: "/coms/", gerundio: "Coming", pron_ger: "/cómin/", past: "Came", pron_past: "/keim/", spanish: "venir" },
    { english: "Cost", pron_pre: "/cost/", third_person: "Costs", pron_thp: "/costs/", gerundio: "Costing", pron_ger: "/cóstin/", past: "Cost", pron_past: "/cost/", spanish: "costar" },
    { english: "Creep", pron_pre: "/crip/", third_person: "Creeps", pron_thp: "/crips/", gerundio: "Creeping", pron_ger: "/crípin/", past: "Crept", pron_past: "/crept/", spanish: "arrastrarse" },
    { english: "Cut", pron_pre: "/cat/", third_person: "Cuts", pron_thp: "/cats/", gerundio: "Cutting", pron_ger: "/cátin/", past: "Cut", pron_past: "/cat/", spanish: "cortar" },
    { english: "Deal", pron_pre: "/dil/", third_person: "Deals", pron_thp: "/dils/", gerundio: "Dealing", pron_ger: "/dílin/", past: "Dealt", pron_past: "/delt/", spanish: "trato / repartir / dar" },
    { english: "Dig", pron_pre: "/dig/", third_person: "Digs", pron_thp: "/digs/", gerundio: "Digging", pron_ger: "/dígin/", past: "Dug", pron_past: "/dag/", spanish: "cavar" },
    { english: "Do", pron_pre: "/du/", third_person: "Does", pron_thp: "/das/", gerundio: "Doing", pron_ger: "/dúin/", past: "Did", pron_past: "/did/", spanish: "hacer" },
    { english: "Draw", pron_pre: "/dra/", third_person: "Draws", pron_thp: "/dras/", gerundio: "Drawing", pron_ger: "/dráin/", past: "Drew", pron_past: "/dru/", spanish: "dibujar" },
    { english: "Dream", pron_pre: "/drim/", third_person: "Dreams", pron_thp: "/drims/", gerundio: "Dreaming", pron_ger: "/drímin/", past: "Dreamt", pron_past: "/dremt/", spanish: "soñar" },
    { english: "Drink", pron_pre: "/drink/", third_person: "Drinks", pron_thp: "/drinks/", gerundio: "Drinking", pron_ger: "/drínkin/", past: "Drank", pron_past: "/drank/", spanish: "beber / tomar" },
    { english: "Drive", pron_pre: "/draiv/", third_person: "Drives", pron_thp: "/draivs/", gerundio: "Driving", pron_ger: "/dráivin/", past: "Drove", pron_past: "/drouv/", spanish: "conducir" },
    { english: "Eat", pron_pre: "/it/", third_person: "Eats", pron_thp: "/its/", gerundio: "Eating", pron_ger: "/ítin/", past: "Ate", pron_past: "/eit/", spanish: "comer" },
    { english: "Fall", pron_pre: "/fol/", third_person: "Falls", pron_thp: "/fols/", gerundio: "Falling", pron_ger: "/fólin/", past: "Fell", pron_past: "/fel/", spanish: "caer" },
    { english: "Feed", pron_pre: "/fid/", third_person: "Feeds", pron_thp: "/fids/", gerundio: "Feeding", pron_ger: "/fídin/", past: "Fed", pron_past: "/fed/", spanish: "alimentar" },
    { english: "Feel", pron_pre: "/fil/", third_person: "Feels", pron_thp: "/fils/", gerundio: "Feeling", pron_ger: "/fílin/", past: "Felt", pron_past: "/felt/", spanish: "sentir" },
    { english: "Fight", pron_pre: "/fait/", third_person: "Fights", pron_thp: "/faits/", gerundio: "Fighting", pron_ger: "/fáitin/", past: "Fought", pron_past: "/fot/", spanish: "pelear / luchar" },
    { english: "Find", pron_pre: "/faind/", third_person: "Finds", pron_thp: "/fainds/", gerundio: "Finding", pron_ger: "/fáindin/", past: "Found", pron_past: "/faund/", spanish: "encontrar" },
    { english: "Fly", pron_pre: "/flai/", third_person: "Flies", pron_thp: "/flais/", gerundio: "Flying", pron_ger: "/fláiin/", past: "Flew", pron_past: "/flu/", spanish: "volar" },
    { english: "Forbid", pron_pre: "/forbid/", third_person: "Forbids", pron_thp: "/forbíds/", gerundio: "Forbidding", pron_ger: "/forbídin/", past: "Forbade", pron_past: "/forbéid/", spanish: "prohibir" },
    { english: "Forget", pron_pre: "/forget/", third_person: "Forgets", pron_thp: "/forgéts/", gerundio: "Forgetting", pron_ger: "/forgétin/", past: "Forgot", pron_past: "/forgót/", spanish: "olvidar" },
    { english: "Forgive", pron_pre: "/forgiv/", third_person: "Forgives", pron_thp: "/forgivs/", gerundio: "Forgiving", pron_ger: "/forgívin/", past: "Forgave", pron_past: "/forgéiv/", spanish: "perdonar" },
    { english: "Forsake", pron_pre: "/forsek/", third_person: "Forsakes", pron_thp: "/forseiks/", gerundio: "Forsaking", pron_ger: "/forseikin/", past: "Forsook", pron_past: "/forsuk/", spanish: "abandonar" },
    { english: "Hide", pron_pre: "/jaid/", third_person: "Hides", pron_thp: "/jaids/", gerundio: "Hiding", pron_ger: "/jáidin/", past: "Hid", pron_past: "/jid/", spanish: "esconder" },
    { english: "Hit", pron_pre: "/jit/", third_person: "Hits", pron_thp: "/jits/", gerundio: "Hitting", pron_ger: "/jítin/", past: "Hit", pron_past: "/jit/", spanish: "golpear" },
    { english: "Hold", pron_pre: "/jold/", third_person: "Holds", pron_thp: "/jolds/", gerundio: "Holding", pron_ger: "/jóldin/", past: "Held", pron_past: "/jeld/", spanish: "sostener / aguantar" },
    { english: "Hurt", pron_pre: "/jert/", third_person: "Hurts", pron_thp: "/jerts/", gerundio: "Hurting", pron_ger: "/jértin/", past: "Hurt", pron_past: "/jert/", spanish: "herir" },
    { english: "Keep", pron_pre: "/kip/", third_person: "Keeps", pron_thp: "/kips/", gerundio: "Keeping", pron_ger: "/kípin/", past: "Kept", pron_past: "/kept/", spanish: "mantener / guardar" },
    { english: "Know", pron_pre: "/nou/", third_person: "Knows", pron_thp: "/nous/", gerundio: "Knowing", pron_ger: "/nóuin/", past: "Knew", pron_past: "/niu/", spanish: "saber / conocer" },
    { english: "Lend", pron_pre: "/lend/", third_person: "Lends", pron_thp: "/lends/", gerundio: "Lending", pron_ger: "/léndin/", past: "Lent", pron_past: "/lent/", spanish: "prestar" },
    { english: "Mistake", pron_pre: "/misteik/", third_person: "Mistakes", pron_thp: "/misteiks/", gerundio: "Mistaking", pron_ger: "/misteikin/", past: "Mistook", pron_past: "/mistuk/", spanish: "equivocarse" },
    { english: "Pay", pron_pre: "/pei/", third_person: "Pays", pron_thp: "/peis/", gerundio: "Paying", pron_ger: "/péiin/", past: "Paid", pron_past: "/peid/", spanish: "pagar" },
    { english: "Quit", pron_pre: "/kuit/", third_person: "Quits", pron_thp: "/kuits/", gerundio: "Quitting", pron_ger: "/kuítin/", past: "Quit", pron_past: "/kuit/", spanish: "dejar / abandonar" },
    { english: "Ride", pron_pre: "/raid/", third_person: "Rides", pron_thp: "/raids/", gerundio: "Riding", pron_ger: "/ráidin/", past: "Rode", pron_past: "/roud/", spanish: "montar / conducir" },
    { english: "Sew", pron_pre: "/su/", third_person: "Sews", pron_thp: "/sous/", gerundio: "Sewing", pron_ger: "/sóuin/", past: "Sewed", pron_past: "/soud/", spanish: "coser" },
    { english: "Shoot", pron_pre: "/shut/", third_person: "Shoots", pron_thp: "/shuts/", gerundio: "Shooting", pron_ger: "/shútin/", past: "Shot", pron_past: "/shot/", spanish: "disparar" },
    { english: "Show", pron_pre: "/shou/", third_person: "Shows", pron_thp: "/shous/", gerundio: "Showing", pron_ger: "/shóuin/", past: "Showed", pron_past: "/shoud/", spanish: "mostrar" },
    { english: "Shrink", pron_pre: "/shrink/", third_person: "Shrinks", pron_thp: "/shrinks/", gerundio: "Shrinking", pron_ger: "/shrrínkin/", past: "Shrank", pron_past: "/shrrank/", spanish: "encoger" },
    { english: "Shut", pron_pre: "/shat/", third_person: "Shuts", pron_thp: "/shats/", gerundio: "Shutting", pron_ger: "/shátin/", past: "Shut", pron_past: "/shat/", spanish: "cerrar" },
    { english: "Sing", pron_pre: "/sing/", third_person: "Sings", pron_thp: "/sings/", gerundio: "Singing", pron_ger: "/síngin/", past: "Sang", pron_past: "/sang/", spanish: "cantar" },
    { english: "Sink", pron_pre: "/sink/", third_person: "Sinks", pron_thp: "/sinks/", gerundio: "Sinking", pron_ger: "/sínkin/", past: "Sank", pron_past: "/sank/", spanish: "hundir" },
    { english: "Sit", pron_pre: "/sit/", third_person: "Sits", pron_thp: "/sits/", gerundio: "Sitting", pron_ger: "/sítin/", past: "Sat", pron_past: "/sat/", spanish: "sentarse" },
    { english: "Sleep", pron_pre: "/slip/", third_person: "Sleeps", pron_thp: "/slips/", gerundio: "Sleeping", pron_ger: "/slípin/", past: "Slept", pron_past: "/slept/", spanish: "dormir" },
    { english: "Slide", pron_pre: "/slaid/", third_person: "Slides", pron_thp: "/slaids/", gerundio: "Sliding", pron_ger: "/sláidin/", past: "Slid", pron_past: "/slid/", spanish: "deslizar / resbalar" },
    { english: "Smell", pron_pre: "/smel/", third_person: "Smells", pron_thp: "/smels/", gerundio: "Smelling", pron_ger: "/smélin/", past: "Smelt", pron_past: "/smelt/", spanish: "oler" },
    { english: "Sow", pron_pre: "/sou/", third_person: "Sows", pron_thp: "/sous/", gerundio: "Sowing", pron_ger: "/sóuin/", past: "Sowed", pron_past: "/soud/", spanish: "sembrar" },
    { english: "Speak", pron_pre: "/spik/", third_person: "Speaks", pron_thp: "/spiks/", gerundio: "Speaking", pron_ger: "/spíkin/", past: "Spoke", pron_past: "/spouk/", spanish: "hablar" },
    { english: "Speed", pron_pre: "/spid/", third_person: "Speeds", pron_thp: "/spids/", gerundio: "Speeding", pron_ger: "/spídin/", past: "Sped", pron_past: "/sped/", spanish: "acelerar" },
    { english: "Spell", pron_pre: "/spel/", third_person: "Spells", pron_thp: "/spels/", gerundio: "Spelling", pron_ger: "/spélin/", past: "Spelt", pron_past: "/spelt/", spanish: "deletrear" },
    { english: "Spend", pron_pre: "/spend/", third_person: "Spends", pron_thp: "/spends/", gerundio: "Spending", pron_ger: "/spéndin/", past: "Spent", pron_past: "/spent/", spanish: "gastar / pasar tiempo" },
    { english: "Spill", pron_pre: "/spil/", third_person: "Spills", pron_thp: "/spils/", gerundio: "Spilling", pron_ger: "/spílin/", past: "Spilt", pron_past: "/spilt/", spanish: "derramar" },
    { english: "Spit", pron_pre: "/spit/", third_person: "Spits", pron_thp: "/spits/", gerundio: "Spitting", pron_ger: "/spítin/", past: "Spat", pron_past: "/spat/", spanish: "escupir" },
    { english: "Split", pron_pre: "/split/", third_person: "Splits", pron_thp: "/splits/", gerundio: "Splitting", pron_ger: "/splítin/", past: "Split", pron_past: "/split/", spanish: "dividir / separar" },
    { english: "Spoil", pron_pre: "/spoil/", third_person: "Spoils", pron_thp: "/spoils/", gerundio: "Spoiling", pron_ger: "/spóilin/", past: "Spoilt", pron_past: "/spoilt/", spanish: "estropear / arruinar" },
    { english: "Spread", pron_pre: "/spred/", third_person: "Spreads", pron_thp: "/spreds/", gerundio: "Spreading", pron_ger: "/sprédin/", past: "Spread", pron_past: "/spred/", spanish: "extender / untar" },
    { english: "Stand", pron_pre: "/stand/", third_person: "Stands", pron_thp: "/stands/", gerundio: "Standing", pron_ger: "/stándin/", past: "Stood", pron_past: "/stud/", spanish: "pararse / estar de pie" },
    { english: "Steal", pron_pre: "/stil/", third_person: "Steals", pron_thp: "/stils/", gerundio: "Stealing", pron_ger: "/stílin/", past: "Stole", pron_past: "/stoul/", spanish: "robar" },
    { english: "Stick", pron_pre: "/stik/", third_person: "Sticks", pron_thp: "/stiks/", gerundio: "Sticking", pron_ger: "/stíkin/", past: "Stuck", pron_past: "/stak/", spanish: "pegar / adherir" },
    { english: "Stink", pron_pre: "/stink/", third_person: "Stinks", pron_thp: "/stinks/", gerundio: "Stinking", pron_ger: "/stínkin/", past: "Stank", pron_past: "/stank/", spanish: "apestar" },
    { english: "Strive", pron_pre: "/straiv/", third_person: "Strives", pron_thp: "/straivs/", gerundio: "Striving", pron_ger: "/stráivin/", past: "Strove", pron_past: "/strouv/", spanish: "esforzarse" },
    { english: "Swear", pron_pre: "/suer/", third_person: "Swears", pron_thp: "/suers/", gerundio: "Swearing", pron_ger: "/suérin/", past: "Swore", pron_past: "/suor/", spanish: "jurar" },
    { english: "Sweep", pron_pre: "/suip/", third_person: "Sweeps", pron_thp: "/suips/", gerundio: "Sweeping", pron_ger: "/suípin/", past: "Swept", pron_past: "/swept/", spanish: "barrer" },
    { english: "Swell", pron_pre: "/suel/", third_person: "Swells", pron_thp: "/suels/", gerundio: "Swelling", pron_ger: "/suélin/", past: "Swelled", pron_past: "/sueld/", spanish: "hinchar" },
    { english: "Swim", pron_pre: "/suim/", third_person: "Swims", pron_thp: "/suims/", gerundio: "Swimming", pron_ger: "/suímin/", past: "Swam", pron_past: "/suam/", spanish: "nadar" },
    { english: "Take", pron_pre: "/teik/", third_person: "Takes", pron_thp: "/teiks/", gerundio: "Taking", pron_ger: "/téikin/", past: "Took", pron_past: "/tuk/", spanish: "tomar / llevar" },
    { english: "Teach", pron_pre: "/tich/", third_person: "Teaches", pron_thp: "/tíchiz/", gerundio: "Teaching", pron_ger: "/tíchin/", past: "Taught", pron_past: "/tot/", spanish: "enseñar" },
    { english: "Tear", pron_pre: "/ter/", third_person: "Tears", pron_thp: "/ters/", gerundio: "Tearing", pron_ger: "/térin/", past: "Tore", pron_past: "/tor/", spanish: "rasgar / arrancar" },
    { english: "Tell", pron_pre: "/tel/", third_person: "Tells", pron_thp: "/tels/", gerundio: "Telling", pron_ger: "/télin/", past: "Told", pron_past: "/told/", spanish: "decir / contar" },
    { english: "Think", pron_pre: "/zink/", third_person: "Thinks", pron_thp: "/zinks/", gerundio: "Thinking", pron_ger: "/zínkin/", past: "Thought", pron_past: "/zot/", spanish: "pensar" },
    { english: "Throw", pron_pre: "/zrou/", third_person: "Throws", pron_thp: "/zrous/", gerundio: "Throwing", pron_ger: "/zróuin/", past: "Threw", pron_past: "/zru/", spanish: "lanzar / tirar" },
    { english: "Understand", pron_pre: "/anderstand/", third_person: "Understands", pron_thp: "/anderstands/", gerundio: "Understanding", pron_ger: "/anderstándin/", past: "Understood", pron_past: "/anderstud/", spanish: "entender" },
    { english: "Undertake", pron_pre: "/anderteik/", third_person: "Undertakes", pron_thp: "/anderteiks/", gerundio: "Undertaking", pron_ger: "/anderteikin/", past: "Undertook", pron_past: "/anderstuk/", spanish: "comprometerse / realizar" },
    { english: "Wake", pron_pre: "/ueik/", third_person: "Wakes", pron_thp: "/ueiks/", gerundio: "Waking", pron_ger: "/uéikin/", past: "Woke", pron_past: "/uouk/", spanish: "despertarse" },
    { english: "Wear", pron_pre: "/uer/", third_person: "Wears", pron_thp: "/uers/", gerundio: "Wearing", pron_ger: "/uérin/", past: "Wore", pron_past: "/uor/", spanish: "usar (ropa) / llevar puesto" },
    { english: "Weave", pron_pre: "/uiv/", third_person: "Weaves", pron_thp: "/uivs/", gerundio: "Weaving", pron_ger: "/uívin/", past: "Wove", pron_past: "/uouv/", spanish: "tejer / entrelazar" },
    { english: "Wet", pron_pre: "/uet/", third_person: "Wets", pron_thp: "/uets/", gerundio: "Wetting", pron_ger: "/uétin/", past: "Wet", pron_past: "/uet/", spanish: "mojar" },
    { english: "Win", pron_pre: "/uin/", third_person: "Wins", pron_thp: "/uins/", gerundio: "Winning", pron_ger: "/uínin/", past: "Won", pron_past: "/uan/", spanish: "ganar" },
    { english: "Write", pron_pre: "/rait/", third_person: "Writes", pron_thp: "/raits/", gerundio: "Writing", pron_ger: "/ráitin/", past: "Wrote", pron_past: "/rout/", spanish: "escribir" }
];

export const examplesRegular = [
    { english: "Arise", present: "Problems arise every day.", past: "A new hope arose yesterday.", gerund: "New questions are arising." },
    { english: "Bear", present: "I can't bear this heat.", past: "She bore three children.", gerund: "He is bearing the weight." },
    { english: "Beat", present: "I beat the drum.", past: "We beat them in the game.", gerund: "My heart is beating fast." },
    { english: "Become", present: "It becomes cold in winter.", past: "He became a doctor.", gerund: "She is becoming famous." },
    { english: "Begin", present: "I begin my work at nine.", past: "The movie began late.", gerund: "It is beginning to rain." },
    { english: "Bite", present: "Does your dog bite?", past: "A mosquito bit me.", gerund: "He is biting his nails." },
    { english: "Bleed", present: "The wound bleeds a lot.", past: "Her nose bled earlier.", gerund: "You are bleeding here." },
    { english: "Blow", present: "The wind blows hard.", past: "He blew out the candles.", gerund: "The wind is blowing now." },
    { english: "Break", present: "I often break things.", past: "She broke her phone.", gerund: "They are breaking the rules." },
    { english: "Breed", present: "They breed horses here.", past: "They bred rabbits last year.", gerund: "She is breeding dogs." },
    { english: "Bring", present: "I bring my lunch.", past: "He brought some wine.", gerund: "What are you bringing?" },
    { english: "Build", present: "We build houses.", past: "They built this bridge.", gerund: "He is building a sandcastle." },
    { english: "Burn", present: "The fire burns bright.", past: "I burnt the toast.", gerund: "The forest is burning." },
    { english: "Buy", present: "I buy fruit every week.", past: "She bought a new car.", gerund: "I am buying the tickets." },
    { english: "Can", present: "I can swim well.", past: "I could run faster then.", gerund: "---" },
    { english: "Catch", present: "I catch the bus.", past: "He caught the ball.", gerund: "She is catching a cold." },
    { english: "Choose", present: "I choose the blue one.", past: "They chose a leader.", gerund: "We are choosing a gift." },
    { english: "Cling", present: "They cling to hope.", past: "The mud clung to his shoes.", gerund: "She is clinging to me." },
    { english: "Come", present: "Come here, please.", past: "They came to the party.", gerund: "Spring is coming." },
    { english: "Cost", present: "It costs too much.", past: "The repair cost a lot.", gerund: "It is costing us a fortune." },
    { english: "Creep", present: "Spiders creep silently.", past: "He crept into the room.", gerund: "The cat is creeping up." },
    { english: "Cut", present: "I cut the bread.", past: "She cut her finger.", gerund: "He is cutting the grass." },
    { english: "Deal", present: "I deal with customers.", past: "We dealt with the issue.", gerund: "She is dealing with stress." },
    { english: "Dig", present: "They dig a hole.", past: "He dug a garden.", gerund: "The dog is digging." },
    { english: "Do", present: "I do my homework.", past: "She did her best.", gerund: "What are you doing?" },
    { english: "Draw", present: "I draw a map.", past: "He drew a picture.", gerund: "She is drawing a flower." },
    { english: "Dream", present: "I dream every night.", past: "I dreamt about you.", gerund: "He is dreaming awake." },
    { english: "Drink", present: "I drink water.", past: "They drank all the juice.", gerund: "She is drinking tea." },
    { english: "Drive", present: "I drive to work.", past: "We drove to the beach.", gerund: "He is driving home." },
    { english: "Eat", present: "I eat an apple.", past: "She ate the pizza.", gerund: "We are eating lunch." },
    { english: "Fall", present: "Leaves fall in autumn.", past: "He fell off the bike.", gerund: "The rain is falling." },
    { english: "Feed", present: "I feed the cat.", past: "She fed the baby.", gerund: "They are feeding the birds." },
    { english: "Feel", present: "I feel happy.", past: "He felt tired.", gerund: "I am feeling better." },
    { english: "Fight", present: "They fight for rights.", past: "We fought for victory.", gerund: "They are fighting again." },
    { english: "Find", present: "I find my keys.", past: "She found her ring.", gerund: "I am finding it difficult." },
    { english: "Fly", present: "Birds fly high.", past: "We flew to London.", gerund: "The plane is flying." },
    { english: "Forbid", present: "I forbid you to go.", past: "They forbade the entry.", gerund: "The law is forbidding it." },
    { english: "Forget", present: "I often forget names.", past: "She forgot the date.", gerund: "I am forgetting everything." },
    { english: "Forgive", present: "I forgive you.", past: "He forgave his friend.", gerund: "She is forgiving him." },
    { english: "Forsake", present: "Never forsake a friend.", past: "He forsook his family.", gerund: "He is forsaking his duty." },
    { english: "Hide", present: "I hide the gift.", past: "She hid behind the door.", gerund: "They are hiding from us." },
    { english: "Hit", present: "I hit the target.", past: "The car hit a tree.", gerund: "He is hitting the ball." },
    { english: "Hold", present: "I hold the baby.", past: "She held my hand.", gerund: "He is holding a meeting." },
    { english: "Hurt", present: "My feet hurt.", past: "The news hurt him.", gerund: "You are hurting my arm." },
    { english: "Keep", present: "I keep my promises.", past: "He kept the money.", gerund: "She is keeping a secret." },
    { english: "Know", present: "I know the answer.", past: "We knew the truth.", gerund: "I am knowing more now." },
    { english: "Lend", present: "I lend him my pen.", past: "She lent me her book.", gerund: "He is lending his car." },
    { english: "Mistake", present: "I often mistake them.", past: "He mistook me for you.", gerund: "You are mistaking the fact." },
    { english: "Pay", present: "I pay the bills.", past: "She paid for dinner.", gerund: "I am paying cash." },
    { english: "Quit", present: "I quit my job.", past: "He quit smoking.", gerund: "They are quitting now." },
    { english: "Ride", present: "I ride my bike.", past: "She rode a horse.", gerund: "We are riding the bus." },
    { english: "Sew", present: "I sew my clothes.", past: "She sewed the button.", gerund: "He is sewing a shirt." },
    { english: "Shoot", present: "I shoot a photo.", past: "They shot the film.", gerund: "He is shooting a video." },
    { english: "Show", present: "I show my work.", past: "She showed me the way.", gerund: "He is showing his talent." },
    { english: "Shrink", present: "Clothes shrink in heat.", past: "The shirt shrank.", gerund: "The market is shrinking." },
    { english: "Shut", present: "I shut the window.", past: "He shut the door.", gerund: "She is shutting the shop." },
    { english: "Sing", present: "I sing a song.", past: "She sang beautifully.", gerund: "They are singing loud." },
    { english: "Sink", present: "Ships sink in storms.", past: "The sun sank slowly.", gerund: "The boat is sinking." },
    { english: "Sit", present: "I sit on the chair.", past: "We sat on the grass.", gerund: "She is sitting down." },
    { english: "Sleep", present: "I sleep eight hours.", past: "He slept like a baby.", gerund: "The cat is sleeping." },
    { english: "Slide", present: "I slide on the ice.", past: "The glass slid off.", gerund: "They are sliding down." },
    { english: "Smell", present: "It smells good.", past: "I smelt something burnt.", gerund: "She is smelling flowers." },
    { english: "Sow", present: "They sow seeds.", past: "He sowed the field.", gerund: "We are sowing the grain." },
    { english: "Speak", present: "I speak English.", past: "He spoke to me.", gerund: "She is speaking now." },
    { english: "Speed", present: "Don't speed here.", past: "He sped away.", gerund: "The car is speeding." },
    { english: "Spell", present: "How do you spell it?", past: "He spelt it wrong.", gerund: "She is spelling her name." },
    { english: "Spend", present: "I spend my money.", past: "We spent the weekend.", gerund: "She is spending time." },
    { english: "Spill", present: "I spill the milk.", past: "She spilt the coffee.", gerund: "Water is spilling out." },
    { english: "Spit", present: "Don't spit here.", past: "He spat on the floor.", gerund: "He is spitting gum." },
    { english: "Split", present: "We split the bill.", past: "They split the wood.", gerund: "The group is splitting." },
    { english: "Spoil", present: "Food spoils fast.", past: "He spoilt the surprise.", gerund: "The rain is spoiling it." },
    { english: "Spread", present: "I spread the butter.", past: "The news spread fast.", gerund: "She is spreading a map." },
    { english: "Stand", present: "I stand here.", past: "They stood up.", gerund: "He is standing there." },
    { english: "Steal", present: "Don't steal.", past: "They stole the car.", gerund: "He is stealing bread." },
    { english: "Stick", present: "Labels stick well.", past: "He stuck the poster.", gerund: "The key is sticking." },
    { english: "Stink", present: "It stinks here.", past: "The room stank.", gerund: "The trash is stinking." },
    { english: "Strive", present: "I strive for success.", past: "She strove to win.", gerund: "We are striving today." },
    { english: "Swear", present: "I swear it's true.", past: "He swore an oath.", gerund: "She is swearing now." },
    { english: "Sweep", present: "I sweep the floor.", past: "She swept the room.", gerund: "He is sweeping the yard." },
    { english: "Swell", present: "My leg swells up.", past: "The river swelled.", gerund: "It is swelling now." },
    { english: "Swim", present: "I swim in the pool.", past: "He swam in the lake.", gerund: "She is swimming fast." },
    { english: "Take", present: "I take the key.", past: "She took my pen.", gerund: "He is taking a photo." },
    { english: "Teach", present: "I teach Spanish.", past: "He taught us math.", gerund: "She is teaching yoga." },
    { english: "Tear", present: "I tear the paper.", past: "She tore her dress.", gerund: "He is tearing the box." },
    { english: "Tell", present: "I tell a story.", past: "He told me a secret.", gerund: "She is telling a lie." },
    { english: "Think", present: "I think about it.", past: "I thought so too.", gerund: "What are you thinking?" },
    { english: "Throw", present: "I throw the ball.", past: "He threw the trash.", gerund: "She is throwing a party." },
    { english: "Understand", present: "I understand you.", past: "We understood that.", gerund: "I am understanding now." },
    { english: "Undertake", present: "I undertake the task.", past: "He undertook the risk.", gerund: "They are undertaking it." },
    { english: "Wake", present: "I wake up at six.", past: "She woke up late.", gerund: "The baby is waking up." },
    { english: "Wear", present: "I wear a hat.", past: "He wore a suit.", gerund: "She is wearing a dress." },
    { english: "Weave", present: "They weave carpets.", past: "She wove a basket.", gerund: "He is weaving a story." },
    { english: "Wet", present: "I wet the towel.", past: "The rain wet us.", gerund: "He is wetting the plant." },
    { english: "Win", present: "I win the race.", past: "We won the prize.", gerund: "They are winning now." },
    { english: "Write", present: "I write a letter.", past: "She wrote a poem.", gerund: "He is writing a book." }
];

export const examplesConectivos = [
    { english: "In fact", pron: "In fact", example: "I love cold weather. In fact, it's my favorite season." },
    { english: "In general", pron: "In yeneral", example: "In general, the food here is very good." },
    { english: "Besides", pron: "Bisais", example: "I'm too tired to go out; besides, it's raining." },
    { english: "By the way", pron: "Bai da uei", example: "I liked your car. By the way, where did you buy it?" },
    { english: "So", pron: "So", example: "It was late, so I went to bed." },
    { english: "Although", pron: "Aldou", example: "Although it was cold, she didn't wear a coat." },
    { english: "Then", pron: "Den", example: "Finish your work, then you can go play." },
    { english: "So then", pron: "So den", example: "So then, what happened after the party?" },
    { english: "Therefore", pron: "Derfor", example: "I forgot my wallet; therefore, I couldn't buy it." },
    { english: "That's right", pron: "Dats rait", example: "You are the winner. That's right!" },
    { english: "However", pron: "Jauever", example: "He studied hard; however, he failed the exam." },
    { english: "At least", pron: "At list", example: "It's expensive, but at least the quality is high." },
    { english: "In other words", pron: "Inoder uords", example: "He is slow; in other words, he needs more time." },
    { english: "Little by little", pron: "Lirol bai Lirol", example: "Little by little, my English is improving." },
    { english: "Step by step", pron: "Step bai step", example: "Follow the manual step by step." },
    { english: "For example", pron: "Forexsampol", example: "I like fruits, for example, apples and pears." },
    { english: "According to", pron: "Acordin tu", example: "According to the news, it will rain tomorrow." },
    { english: "Without a doubt", pron: "Uidaradaut", example: "She is, without a doubt, the best student." },
    { english: "Hands down", pron: "Jen daun", example: "This is hands down the best pizza in town." },
    { english: "Unless", pron: "Anles", example: "I won't go unless you come with me." },
    { english: "Somehow", pron: "Som jau", example: "We will finish this project somehow." },
    { english: "I agree", pron: "Ai agri", example: "I agree with your point of view." },
    { english: "Kidding", pron: "Kirin", example: "Don't get angry, I'm just kidding!" },
    { english: "I know what you mean", pron: "Ai nou uat iu min", example: "Life is hard. I know what you mean." },
    { english: "On second thought", pron: "On second zot", example: "I wanted coffee, but on second thought, I'll have tea." },
    { english: "Afford", pron: "Aford", example: "I can't afford to buy a new house right now." },
    { english: "By any chance", pron: "Bai eni chens", example: "Do you have a pen by any chance?" },
    { english: "In the meantime", pron: "In da min taim", example: "The bus is late; in the meantime, let's talk." },
    { english: "Meanwhile", pron: "Min uail", example: "I was cooking; meanwhile, he was watching TV." },
    { english: "While", pron: "Uail", example: "I fell asleep while I was reading." },
    { english: "Instead", pron: "Insted", example: "There was no milk, so I had water instead." },
    { english: "Instead of", pron: "Insterof", example: "I'll take the stairs instead of the elevator." },
    { english: "On you", pron: "On iu", example: "Lunch is on you today, right?" },
    { english: "Let me get this straight", pron: "Let mi get distreit", example: "Let me get this straight, you lost the keys?" },
    { english: "It's a good thing", pron: "Itsa gud zin", example: "It's a good thing we brought an umbrella." },
    { english: "Changed my mind", pron: "Chench mai maind", example: "I was going to stay, but I changed my mind." },
    { english: "What I'd give to", pron: "Uarai giv tu", example: "What I'd give to be on the beach right now!" },
    { english: "Allow me", pron: "Alou mi", example: "Allow me to introduce my sister." },
    { english: "I'm afraid yes", pron: "Aimafreid ies", example: "Are we lost? I'm afraid yes." },
    { english: "I'm afraid not", pron: "Aimafreid nat", example: "Can you help me? I'm afraid not." },
    { english: "Among", pron: "Among", example: "The house is hidden among the trees." },
    { english: "Between", pron: "Bituin", example: "The ball is between the two cars." },
    { english: "Odds", pron: "Ods", example: "The odds of winning are very low." },
    { english: "Toward", pron: "Touard", example: "They are walking toward the park." },
    { english: "Despite", pron: "Dispait", example: "Despite the rain, we went for a run." },
    { english: "Due to", pron: "Du tu", example: "The flight was canceled due to the storm." },
    { english: "Nevertheless", pron: "Never da les", example: "It's risky; nevertheless, I want to try." },
    { english: "On the other hand", pron: "On oder jend", example: "It's expensive; on the other hand, it lasts forever." },
    { english: "Otherwise", pron: "Oder uais", example: "Hurry up, otherwise you'll be late." },
    { english: "Speechless", pron: "Spichles", example: "Her beauty left me speechless." },
    { english: "Yet again", pron: "iet Aguen", example: "He forgot his keys yet again." },
    { english: "For good", pron: "For gud", example: "She is moving to Spain for good." },
    { english: "Fortunately", pron: "Forchenli", example: "Fortunately, the accident wasn't serious." },
    { english: "Unfortunately", pron: "Anforchenli", example: "Unfortunately, I can't attend the wedding." },
    { english: "Obviously", pron: "Obiusli", example: "He is obviously lying." },
    { english: "Undoubtedly", pron: "Andaurebli", example: "She is undoubtedly the best for the job." },
    { english: "Surely", pron: "Shurli", example: "Surely you can't be serious!" },
    { english: "Indeed", pron: "Indid", example: "Thank you very much. It was a great help indeed." },
    { english: "Apparently", pron: "Aperenli", example: "Apparently, they are moving next month." },
    { english: "Possibly", pron: "Posibli", example: "I will possibly arrive late tonight." },
    { english: "Currently", pron: "Kurrentli", example: "He is currently working on a new book." },
    { english: "Actually", pron: "Acshuli", example: "I actually live near the airport." },
    { english: "Mostly", pron: "Moszli", example: "The students are mostly from Europe." },
    { english: "Practically", pron: "Practicli", example: "The room was practically empty." },
    { english: "All in all", pron: "Olin ol", example: "All in all, it was a successful day." },
    { english: "To sum up", pron: "Tu samap", example: "To sum up, we need to save more money." },
    { english: "Eventually", pron: "Evenshuali", example: "Keep trying and you will win eventually." },
    { english: "Nowadays", pron: "Nauadeis", example: "Nowadays, everyone has a smartphone." },
    { english: "Last but not least", pron: "Last bat nat list", example: "Last but not least, thank you for coming." },
    { english: "From now on", pron: "From nauon", example: "From now on, I will wake up earlier." },
    { english: "Once in a while", pron: "Uansinauail", example: "I eat fast food once in a while." },
    { english: "That's why", pron: "Dats uay", example: "I'm sick, that's why I'm not going." },
    { english: "Just in case", pron: "Yost in keis", example: "Take an umbrella just in case." },
    { english: "In spite of", pron: "In spairof", example: "In spite of the noise, I slept well." },
    { english: "That being said", pron: "Dat bin sed", example: "It's far. That being said, it's worth the trip." },
    { english: "Uncalled for", pron: "Ancaled for", example: "That rude comment was completely uncalled for." },
    { english: "By all means", pron: "Bai ol mins", example: "If you need help, by all means ask me." },
    { english: "By no means", pron: "Bai no mins", example: "It is by no means an easy task." },
    { english: "From what I see", pron: "From uarai si", example: "From what I see, the situation is improving." }
];